env: local

storage:
    db_host: "localhost"
    db_port: 5432
    db_user: "eventor"
    db_pass: "password"
    db_name: "eventor_db"

http_server:
    http_address: "localhost:8080"
    timeout: "4s"
    idle_timeout: "60s"

jwt:
    secret: "your-super-secret-jwt-key-minimum-32-characters-length"
    access_token_ttl: "15m"
    refresh_token_ttl: "7d"
